
/**************************************************************
 *	
 *	DoorSound, 8 bit, 11025Hz,
 *	1 channel, 29845 bytes/channel
 *	Total Size: 1 * 29845 + 4 (header) = 29889 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sandra\Desktop\GeorgiaTech\1.Fall2018\CS\Milestones\M4\Final\Music\DoorSound.wav
 *	Time-stamp: Mon Nov 26 23:27:13 2018
 *	
 **************************************************************/

#ifndef __DOORSOUNDH__
#define __DOORSOUNDH__

#define DOORSOUNDFREQ 11025
#define DOORSOUNDLEN 29845

extern const unsigned char DoorSound[29845];

#endif /* __DOORSOUNDH__ */
