
/**************************************************************
 *	
 *	HouseOfCards, 8 bit, 22050Hz,
 *	1 channel, 3581568 bytes/channel
 *	Total Size: 1 * 3581568 + 4 (header) = 3581612 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sandra\Desktop\GeorgiaTech\1.Fall2018\CS\Milestones\M4\Final\Music\HouseOfCards.wav
 *	Time-stamp: Thu Nov 29 23:13:07 2018
 *	
 **************************************************************/

#ifndef __HOUSEOFCARDSH__
#define __HOUSEOFCARDSH__

#define HOUSEOFCARDSFREQ 22050
#define HOUSEOFCARDSLEN 3581568

extern const unsigned char HouseOfCards[3581568];

#endif /* __HOUSEOFCARDSH__ */
