
/**************************************************************
 *	
 *	I_Need_U, 8 bit, 22050Hz,
 *	1 channel, 3720317 bytes/channel
 *	Total Size: 1 * 3720317 + 4 (header) = 3720361 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sandra\Desktop\GeorgiaTech\1.Fall2018\CS\Milestones\Final Project\Music\I Need U.wav
 *	Time-stamp: Fri Nov 30 16:55:44 2018
 *	
 **************************************************************/

#ifndef __INEEDUH__
#define __INEEDUH__

#define INEEDUFREQ 22050
#define INEEDULEN 3720317

extern const unsigned char INeedU[3720317];

#endif /* __INEEDUH__ */
