
/**************************************************************
 *	
 *	KeySound, 8 bit, 22050Hz,
 *	1 channel, 9647 bytes/channel
 *	Total Size: 1 * 9647 + 4 (header) = 9691 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sandra\Desktop\GeorgiaTech\1.Fall2018\CS\Milestones\M4\Final\Music\KeySound.wav
 *	Time-stamp: Thu Nov 29 23:12:53 2018
 *	
 **************************************************************/

#ifndef __KEYSOUNDH__
#define __KEYSOUNDH__

#define KEYSOUNDFREQ 22050
#define KEYSOUNDLEN 9647

extern const unsigned char KeySound[9647];

#endif /* __KEYSOUNDH__ */
