
/**************************************************************
 *	
 *	Run, 8 bit, 11025Hz,
 *	1 channel, 1971936 bytes/channel
 *	Total Size: 1 * 1971936 + 4 (header) = 1971980 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sandra\Desktop\GeorgiaTech\1.Fall2018\CS\Milestones\M3\Current\Run.wav
 *	Time-stamp: Wed Nov 21 15:27:22 2018
 *	
 **************************************************************/

#ifndef __RUNH__
#define __RUNH__

#define RUNFREQ 11025
#define RUNLEN 1971936

extern const unsigned char Run[1971936];

#endif /* __RUNH__ */
