
/**************************************************************
 *	
 *	Sea, 8 bit, 11025Hz,
 *	1 channel, 898835 bytes/channel
 *	Total Size: 1 * 898835 + 4 (header) = 898879 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sandra\Desktop\GeorgiaTech\1.Fall2018\CS\Milestones\M3\Current\Sea.wav
 *	Time-stamp: Wed Nov 21 15:27:33 2018
 *	
 **************************************************************/

#ifndef __SEAH__
#define __SEAH__

#define SEAFREQ 11025
#define SEALEN 898835

extern const unsigned char Sea[898835];

#endif /* __SEAH__ */
